[Draft] Add type declaration
auraphp/Aura.Filter pull request #151
Opened 2022-02-11 17:42 UTC by harikt

Using rector to make the necessary changes to code for type hint and other auto rules.

Current `rector.php`

```
<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::PATHS, [
        __DIR__ . '/src'
    ]);

    $parameters->set(Option::SKIP, [
        'src/Locator/ValidateLocator.php',
        'src/Locator/SanitizeLocator.php',
    ]);

    $parameters->set(Option::AUTO_IMPORT_NAMES, true);

    $containerConfigurator->import(SetList::PHP_72);
    $containerConfigurator->import(SetList::TYPE_DECLARATION);
    $containerConfigurator->import(SetList::TYPE_DECLARATION_STRICT);
};
```

2022-02-13 02:06 UTC, koriym commented on src/Rule/Validate/Email.php
> +                        } elseif ((is_array(preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT)) || preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT) instanceof Countable ?
preg_grep() never return Countable?
It also makes the code harder to read.

2022-02-13 02:06 UTC, koriym commented on src/Rule/Validate/Email.php
> +                    if ((is_array($result) || $result instanceof Countable ? count($result) : 0) === 0) {
dns_get_record never return  Countable?

2022-02-13 02:37 UTC, koriym commented on src/Rule/Validate/Email.php
> +    public const VALID_CATEGORY = 1;
Isn't "protected"?

2022-02-13 02:37 UTC, koriym commented on src/Rule/Validate/Email.php
> +    public const VALID_CATEGORY = 1;
The const of this class is only used within this class.

2022-02-13 02:43 UTC, koriym requested changes

2022-02-13 02:43 UTC, koriym commented on src/Rule/AbstractCharCase.php
>       * @return int
```suggestion
     * @return int
```
The original declaration is wrong.

2022-02-13 02:45 UTC, koriym requested changes

2022-02-13 02:45 UTC, koriym commented on src/Rule/AbstractCharCase.php
>       * @return int
```suggestion
```
The original type declaration is wrong.

2022-02-13 06:51 UTC, harikt commented
Thanks for your wonderful review . I will check when I get sometime

2022-02-14 17:29 UTC, harikt commented on src/Rule/Validate/Email.php
> +                        } elseif ((is_array(preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT)) || preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT) instanceof Countable ?
preg_grep will be returning array, which means it is countable. But I agree we don't need to use Countable there. But preg_grep can also return false. So checking is_array seems a nice approach here. I will look more closely into this again.

2022-02-19 07:31 UTC, koriym approved these changes

2022-02-19 09:08 UTC, harikt commented on src/Rule/Validate/Email.php
> +                        } elseif ((is_array(preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT)) || preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT) instanceof Countable ?
Hi @koriym , 

I am going to modify the code as 

```
} elseif (is_array(preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT)) && count(preg_grep('/^[0-9A-Fa-f]{0,4}$/', $matchesIP, PREG_GREP_INVERT)) !== 0) {
```

that will make sure there is no count(false)

2022-02-19 09:20 UTC, merged

2022-02-19 09:21 UTC, harikt commented
Thank you @koriym . I have made the necessary changes you have requested for. In case you find any issues let me know.